name: Process Changed Files

on:
  push:
    branches:
      - main

jobs:
  process_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Fetch main branch
        run: git fetch origin main

      - name: Identify changed files
        id: filter_changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            added:
              type: added
              paths: '**'
            modified:
              type: modified
              paths: '**'
            deleted:
              type: deleted
              paths: '**'

      - name: Process added files
        if: steps.filter_changes.outputs.added != ''
        run: |
          echo "Processing added files..."
          for file in ${{ steps.filter_changes.outputs.added }}; do
            URL="https://github.com/${{ github.repository }}/blob/main/$file"
            echo "File: $file"
            echo "Operation: added"
            echo "URL: $URL"
            # Replace this with your API call to process each file
            # RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{"url":"'"$URL"'","operation":"added"}' https://yourapi.example.com/endpoint)
            # echo "API Response: $RESPONSE"
          done

      - name: Process modified files
        if: steps.filter_changes.outputs.modified != ''
        run: |
          echo "Processing modified files..."
          for file in ${{ steps.filter_changes.outputs.modified }}; do
            URL="https://github.com/${{ github.repository }}/blob/main/$file"
            echo "File: $file"
            echo "Operation: modified"
            echo "URL: $URL"
            # Replace this with your API call to process each file
            # RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{"url":"'"$URL"'","operation":"modified"}' https://yourapi.example.com/endpoint)
            # echo "API Response: $RESPONSE"
          done

      - name: Process deleted files
        if: steps.filter_changes.outputs.deleted != ''
        run: |
          echo "Processing deleted files..."
          for file in ${{ steps.filter_changes.outputs.deleted }}; do
            URL="https://github.com/${{ github.repository }}/blob/main/$file"
            echo "File: $file"
            echo "Operation: deleted"
            echo "URL: $URL"
            # Replace this with your API call to process each file
            # RESPONSE=$(curl -X POST -H "Content-
