name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  process_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - Checkout completed
        run: echo "Repository checked out successfully."

      - name: Fetch latest commits
        run: |
          echo "Fetching latest commits..."
          git fetch origin main
          echo "Fetch completed."

      - name: Get list of changed files
        id: changes
        run: |
          echo "Getting list of changed files..."
          git diff --name-status HEAD^ HEAD > changes.txt
          echo "Changed files list generated."

      - name: Debug - Changed files list
        run: |
          echo "List of changed files:"
          cat changes.txt

      - name: Process changed files
        id: process_changes
        run: |
          echo "Processing changed files..."
          while IFS= read -r line; do
            OPERATION=$(echo $line | awk '{print $1}')
            FILE_PATH=$(echo $line | awk '{print $2}')
            URL="https://github.com/${{ github.repository }}/blob/main/$FILE_PATH"
            case $OPERATION in
              A) TYPE="new file added";;
              D) TYPE="deleted";;
              M) TYPE="updated";;
            esac
            echo "File: $FILE_PATH"
            echo "Operation: $TYPE"
            echo "URL: $URL"
            echo "::set-output name=file::$FILE_PATH"
            echo "::set-output name=operation::$TYPE"
            echo "::set-output name=url::$URL"
            RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{"url":"'"$URL"'","index":"Langchaintest","operation":"'"$TYPE"'"}' https://yourapi.example.com/endpoint)
            echo "API Response: $RESPONSE"
          done < changes.txt

      - name: Debug - Processing completed
        run: echo "File processing completed."
        
      - name: Post results
        run: echo "Files processed successfully."
