name: Push to main branch

on:
  push:
    branches:
      - main

jobs:
  process_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Fetch main branch
        run: git fetch origin main

      - name: Identify changed files
        id: changed_files
        uses: tj-actions/changed-files@v9
        with:
          base: origin/main  # Specify the base branch to compare against

      - name: Debug - Changed files list
        run: |
          echo "List of changed files:"
          echo "${{ steps.changed_files.outputs.files }}"

      - name: Process changed files
        id: process_changes
        run: |
          echo "Processing changed files..."
          for file_path in ${{ steps.changed_files.outputs.files }}; do
            echo "Processing $file_path..."
            # Add your processing logic here (e.g., notify, test, deploy)
            # Example: Notify or perform actions based on each file_path
            URL="https://github.com/${{ github.repository }}/blob/main/$file_path"
            TYPE=$(git log -1 --pretty=format:"%h %s" -- $file_path)
            RESPONSE=$(curl -X POST -H "Content-Type: application/json" -d '{"url":"'"$URL"'","commit":"'"$TYPE"'"}' https://yourapi.example.com/endpoint)
            echo "API Response: $RESPONSE"
          done

      - name: Debug - Processing completed
        run: echo "File processing completed."

      - name: Post results
        run: echo "Files processed successfully."
